### ISSUE TITLE
bugs s.o nativo

### ISSUE THREAD

**Issue by Juanchith** [ZLCube/KaliBspwm#8]
Could you do it for native Kali Linux? On a virtual machine, there is no problem, but when I install it on my native Kali Linux system, the battery is not displayed, the IP is not loaded, HTB is not shown, the Wi-Fi menu does not appear to connect to any Wi-Fi, and there are some bugs.

**Comment by lhackercoder** [comment]
mismo error aun buscando solucion

**Comment by ZLCube** [comment]
The most recent repository is: https://github.com/ZLCube/AutoBspwm, also i encourage yoy to learn how to use this environment in a virtual machine as the issues you comment have an easy fix and most of them are not repository issues but they are configuratiosn that will depend on your side. 

1) The polybar scripts that display the IP are `~/.config/bin/ethernet_status.sh` in which you will need to replace the eth0 with the wifi interface of your ocmputer (You can check this with `ifconfig` command) 

2) There is no batery module on this repo, you will need to set it up on your own but a command you can use to check the batery level is `upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage` an easy shortcut for this could be to add it asn an alias on your zshrc config file, you can do this by editing the `~/.zshrc` file and asign an alias like `alias batery='upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage'`

3) There is no wifi menu in BSPWM but you can install wpagui with `sudo apt install -y wpagui` and you can run it with `wpa_gui` command or open it through the application browser. 

You can check the recent closed issues at https://github.com/ZLCube/AutoBspwm/issue
